# Description: Get the version of a player
# Authors: Jake
# Dependencies: Skript-Reflect (https://github.com/TPGamesNL/skript-reflect/releases/), ViaVersion (https://github.com/ViaVersion/ViaVersion/releases)
# Example Usage: send "%player's version%"


import:
    com.viaversion.viaversion.api.protocol.version.ProtocolVersion

player property version:
    get: 
        return ProtocolVersion.getProtocol(protocol version of expr-1).getName()